### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by steveoh** [agrc/agrc.widgets#66]
I would like to give our widgets some documentation. I think they deserve it. I think the dojo doc parser is horrible and would like to try something pretty, like [docco](http://jashkenas.github.io/docco/). 

I like the way it mixes code with the documentation side by side and it would be a good fit.

It could make a good gh-pages branch then as well.

**Comment by stdavis** [comment]
Sounds good to me.

**Comment by stdavis** [comment]
We do need better documentation standards but this repo isn't the place to do it anymore.
