### ISSUE TITLE
BaseMap router spatial reference

### ISSUE THREAD

**Issue by steveoh** [agrc/agrc.widgets#75]
the basemap router always creates a point with the 26912 spatial reference. The point is created before the map is loaded so you can't get the spatial reference from the layers. You _could_ get the spatialReference from the extent which gets set in the constructor if you moved the router init call below the default extent initialization.

**Comment by stdavis** [comment]
What about just changing the router to be web mercator? Are we ever going to want it to be UTM in the future?

**Comment by steveoh** [comment]
I don't know, it seems more useful if it just works with the SR it's using. It also doesn't seem much harder to make that happen.

**Comment by stdavis** [comment]
Moved to: https://github.com/agrc-widgets/map-tools/issues/2
